/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ElButton: typeof import('element-plus/es')['ElButton']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElSpace: typeof import('element-plus/es')['ElSpace']
    HelloWorld: typeof import('./../src/components/HelloWorld.vue')['default']
    IEpAddLocation: typeof import('~icons/ep/add-location')['default']
    IEpAim: typeof import('~icons/ep/aim')['default']
    IEpCircleCheckFilled: typeof import('~icons/ep/circle-check-filled')['default']
    IEpDocument: typeof import('~icons/ep/document')['default']
    IEpS: typeof import('~icons/ep/s')['default']
    IEpSe: typeof import('~icons/ep/se')['default']
    IEpSearch: typeof import('~icons/ep/search')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
